# Generated by Django 3.2.20 on 2024-01-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotquery',
            name='feedback',
            field=models.TextField(default='', max_length=500),
        ),
    ]
