name: Deploy OpenEdx to Staging
on:
  push:
    branches:
      - "staging"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy docker image to EC2
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.STAG_IP }}
          username: openedx
          key: ${{ secrets.STAG_KEY }}
          port: 22
          script: |
            export PATH='/home/openedx/.local/bin:/home/openedx/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
            docker pull 848839979695.dkr.ecr.ap-southeast-1.amazonaws.com/lms:15.3.6
            echo -e "y\n\n\n\n\n\ny" | tutor local launch
